# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-22 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='grade',
            field=models.CharField(default='0', max_length=1),
        ),
    ]
