# Generated by Django 2.2.1 on 2019-05-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignModel', '0002_auto_20190522_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
