# Generated by Django 2.2.1 on 2019-05-24 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignModel', '0003_auto_20190524_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='已有课程'),
        ),
    ]
