# Generated by Django 2.2.1 on 2019-05-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignModel', '0005_auto_20190524_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
