# Generated by Django 2.2.1 on 2019-05-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SignModel', '0006_auto_20190524_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='phone_num',
            field=models.CharField(max_length=13, unique=True, verbose_name='电话号码'),
        ),
    ]
